FROM node:20-alpine

WORKDIR /app

RUN corepack enable


COPY package.json .
COPY pnpm-lock.yaml .
COPY pnpm-workspace.yaml .
COPY turbo.json .


COPY packages ./packages

COPY apps/ws-server ./apps/ws-server

RUN pnpm install


RUN pnpm run generate:db

RUN pnpm run build 

EXPOSE 8000

CMD ["pnpm", "start:ws"]