FROM node:20-alpine

WORKDIR /app

RUN corepack enable


COPY package.json .
COPY pnpm-lock.yaml .
COPY pnpm-workspace.yaml .
COPY turbo.json .


COPY packages ./packages

COPY apps/web ./apps/web

RUN pnpm install

RUN pnpm run build 

EXPOSE 3000

CMD ["pnpm", "start:web"]