name: CollabCanvas CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login into the docker  hub 
        uses: docker/Login-actions@v4 
        with: 
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build the image and push 
        uses: docker/build-push-actions@v4 
        with : 
         content: .
         push: true
         tag: ${{ secrets.DOCKERHUB_USERNAME }}/CollabCanvas:latest  